### PR TITLE
config_loader: Support ssl when an url is used

### PR DESCRIPTION
**Pull request by alubbe**
We ran into this issue while trying to deploy to heroku, which requires ssl for the connection.

Please let me know if this changeset is sufficient or whether you see a simple way to update the existing tests.

### CODE REVIEW

**Comment by alubbe** [comment]
Hey @BlueHotDog any chance you could take a look at this PR? It'd be great to get this merged and published. The diff is fairly straight forward. Let me know if you have any questions!

**Comment by BlueHotDog** [comment]
Looks good, but i'm no longer maintaining the project.
@joaosa can you please take a look and approve?

**Comment by alubbe** [comment]
pinging @joaosa

**Comment by alubbe** [comment]
so we have two approvals, how about it @joaosa  ? :)

**Comment by RWOverdijk** [comment]
I can merge, but I can't publish.

**Comment by joaosa** [comment]
@RWOverdijk what is your npm username?

**Comment by RWOverdijk** [comment]
Same as here. But honestly, preferably I'm not the one maintaining this. I have my own ORM with a much smarter migration system. I'm not invested enough here to maintain this.

**Comment by joaosa** [comment]
@RWOverdijk fair enough. It'd be good if we could find a full-time maintainer. 

I released this as 2.1.0 in the meantime.

**Comment by RWOverdijk** [comment]
@joaosa I agree.

**Pull request merged**
